- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy expense
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: remove default nginx files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create nginx files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend.zip
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes