- name: backend
  hosts: BE
  become: yes
  tasks:
    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: enable nodejs
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: copy backend
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: add user
      ansible.builtin.user:
        name: expense
    - name: delete old dir
      ansible.builtin.file:
        path: /app
        state: absent
    - name: new dir
      ansible.builtin.file:
        path: /app
        state: directory
    - name: unzip bakend
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes
    - name: npm install
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: intsall mysql
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: loadschema
      ansible.builtin.shell: mysql -h 172.31.41.56 -uroot -pExpenseApp@1 < /app/schema/backend.sql
    - name: backend
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        demon-reload: yes