- name : sql
  hosts: sql
  become: yes
  tasks:
    - name: disable default mysql
      ansible.builtin.shell: dnf module disable mysql -y
    - name: copy repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    - name: install sql
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present
    - name: start sql
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes
    - name: mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1



